repos:
  - repo: https://github.com/madjar-code/CV_API_Cegeka_Task
    rev: v3.9.2
    hooks:
      - id: flake8
        exclude: migrations,settings
        args: [--max-line-length=79, --ignore=F401]